Categories:
- Name: AI_and_Machine_Learning
  Services:
  - Source: AI Hub
    Target: AI_Hub
  - Source: AI Platform Data Labeling Service
    Target: AI_Platform_Data_Labeling_Service
  - Source: AI Platform
    Target: AI_Platform
  - Source: Advanced Solutions Lab
    Target: Advanced_Solutions_Lab
  - Source: AutoML Natural Language
    Target: AutoML_Natural_Language
  - Source: AutoML Tables
    Target: AutoML_Tables
  - Source: AutoML Translation
    Target: AutoML_Translation
  - Source: AutoML Video Intelligence
    Target: AutoML_Video_Intelligence
  - Source: AutoML Vision
    Target: AutoML_Vision
  - Source: Cloud AutoML
    Target: Cloud_AutoML
  - Source: Cloud Inference API
    Target: Cloud_Inference_API
  - Source: Cloud Jobs API
    Target: Cloud_Jobs_API
  - Source: Cloud Natural Language API
    Target: Cloud_Natural_Language_API
  - Source: Cloud Speech-to-Text
    Target: Cloud_Speech_to_Text
  - Source: Cloud TPU
    Target: Cloud_TPU
  - Source: Cloud Text-to-Speech
    Target: Cloud_Text_to_Speech
  - Source: Cloud Translation API
    Target: Cloud_Translation_API
  - Source: Cloud Video Intelligence API
    Target: Cloud_Video_Intelligence_API
  - Source: Cloud Vision API
    Target: Cloud_Vision_API
  - Source: Dialog Flow Enterprise Edition
    Target: Dialog_Flow_Enterprise_Edition
  - Source: Recommendations AI
    Target: Recommendations_AI
  SourceDir: AI_and_Machine_Learning
- Name: API_Management
  Services:
  - Source: API Analytics
    Target: API_Analytics
  - Source: API Monetization
    Target: API_Monetization
  - Source: Apigee API Platform
    Target: Apigee_API_Platform
  - Source: Apigee Sense
    Target: Apigee_Sense
  - Source: Cloud Endpoints
    Target: Cloud_Endpoints
  - Source: Developer Portal
    Target: Developer_Portal
  SourceDir: API_Management
- Name: Compute
  Services:
  - Source: App Engine
    Target: App_Engine
  - Source: Cloud Functions
    Target: Cloud_Functions
  - Source: Cloud Run
    Target: Cloud_Run
  - Source: Compute Engine
    Target: Compute_Engine
  - Source: Container-Optimized OS
    Target: Container_Optimized_OS
  - Source: GKE On-Prem
    Target: GKE_On_Prem
  - Source: GPU
    Target: GPU
  - Source: Kubernetes Engine
    Target: Kubernetes_Engine
  SourceDir: Compute
- Name: Data_Analytics
  Services:
  - Source: BigQuery
    Target: BigQuery
  - Source: Cloud Composer
    Target: Cloud_Composer
  - Source: Cloud Data Catalog
    Target: Cloud_Data_Catalog
  - Source: Cloud Data Fusion
    Target: Cloud_Data_Fusion
  - Source: Cloud Dataflow
    Target: Cloud_Dataflow
  - Source: Cloud Datalab
    Target: Cloud_Datalab
  - Source: Cloud Dataprep
    Target: Cloud_Dataprep
  - Source: Cloud Dataproc
    Target: Cloud_Dataproc
  - Source: Cloud PubSub
    Target: Cloud_PubSub
  - Source: Genomics
    Target: Genomics
  SourceDir: Data_Analytics
- Name: Databases
  Services:
  - Source: Cloud Bigtable
    Target: Cloud_Bigtable
  - Source: Cloud Datastore
    Target: Cloud_Datastore
  - Source: Cloud Firestore
    Target: Cloud_Firestore
  - Source: Cloud Memorystore
    Target: Cloud_Memorystore
  - Source: Cloud SQL
    Target: Cloud_SQL
  - Source: Cloud Spanner
    Target: Cloud_Spanner
  SourceDir: Databases
- Name: Developer_Tools
  Services:
  - Source: Cloud Build
    Target: Cloud_Build
  - Source: Cloud Code for IntelliJ
    Target: Cloud_Code_for_IntelliJ
  - Source: Cloud Code
    Target: Cloud_Code
  - Source: Cloud SDK
    Target: Cloud_SDK
  - Source: Cloud Scheduler
    Target: Cloud_Scheduler
  - Source: Cloud Source Repositories
    Target: Cloud_Source_Repositories
  - Source: Cloud Tasks
    Target: Cloud_Tasks
  - Source: Cloud Test Lab
    Target: Cloud_Test_Lab
  - Source: Cloud Tools for Eclipse
    Target: Cloud_Tools_for_Eclipse
  - Source: Cloud Tools for PowerShell
    Target: Cloud_Tools_for_PowerShell
  - Source: Cloud Tools for Visual Studio
    Target: Cloud_Tools_for_Visual_Studio
  - Source: Container Registry
    Target: Container_Registry
  - Source: Gradle App Engine Plugin
    Target: Gradle_App_Engine_Plugin
  - Source: IDE Plugins
    Target: IDE_Plugins
  - Source: Maven App Engine Plugin
    Target: Maven_App_Engine_Plugin
  SourceDir: Developer_Tools
- Name: Hybrid_and_Multi_Cloud
  Services:
  - Source: Stackdriver
    Target: Stackdriver
  - Source: Traffic Director
    Target: Traffic_Director
  SourceDir: Hybrid_and_Multi_Cloud
- Name: Internet_of_Things
  Services:
  - Source: Cloud IoT Core
    Target: Cloud_IoT_Core
  SourceDir: Internet_of_Things
- Name: Management_Tools
  Services:
  - Source: Cloud APIs
    Target: Cloud_APIs
  - Source: Cloud Billing API
    Target: Cloud_Billing_API
  - Source: Cloud Console
    Target: Cloud_Console
  - Source: Cloud Deployment Manager
    Target: Cloud_Deployment_Manager
  - Source: Cloud Mobile App
    Target: Cloud_Mobile_App
  - Source: Cloud Service Mesh
    Target: Cloud_Service_Mesh
  - Source: Cloud Shell
    Target: Cloud_Shell
  - Source: Debugger
    Target: Debugger
  - Source: Error Reporting
    Target: Error_Reporting
  - Source: Logging
    Target: Logging
  - Source: Monitoring
    Target: Monitoring
  - Source: Profiler
    Target: Profiler
  - Source: Stackdriver
    Target: Stackdriver
    ZComment: '******* Duplicate target name, must be made unique for All.puml ********'
  - Source: Trace
    Target: Trace
  SourceDir: Management_Tools
- Name: Migration
  Services:
  - Source: Transfer Appliance
    Target: Transfer_Appliance
  SourceDir: Migration
- Name: Networking
  Services:
  - Source: Cloud Armor
    Target: Cloud_Armor
  - Source: Cloud CDN
    Target: Cloud_CDN
  - Source: Cloud DNS
    Target: Cloud_DNS
  - Source: Cloud External IP Addresses
    Target: Cloud_External_IP_Addresses
  - Source: Cloud Firewall Rules
    Target: Cloud_Firewall_Rules
  - Source: Cloud Load Balancing
    Target: Cloud_Load_Balancing
  - Source: Cloud NAT
    Target: Cloud_NAT
  - Source: Cloud Network
    Target: Cloud_Network
  - Source: Cloud Router
    Target: Cloud_Router
  - Source: Cloud Routes
    Target: Cloud_Routes
  - Source: Cloud VPN
    Target: Cloud_VPN
  - Source: Dedicated Interconnect
    Target: Dedicated_Interconnect
  - Source: Partner Interconnect
    Target: Partner_Interconnect
  - Source: Premium Network Tier
    Target: Premium_Network_Tier
  - Source: Standard Network Tier
    Target: Standard_Network_Tier
  - Source: Traffic Director
    Target: Traffic_Director
    ZComment: '******* Duplicate target name, must be made unique for All.puml ********'
  - Source: Virtual Private Cloud
    Target: Virtual_Private_Cloud
  SourceDir: Networking
- Name: Security
  Services:
  - Source: Cloud IAM
    Target: Cloud_IAM
  - Source: Cloud Resource Manager
    Target: Cloud_Resource_Manager
  - Source: Cloud Security Command Center
    Target: Cloud_Security_Command_Center
  - Source: Cloud Security Scanner
    Target: Cloud_Security_Scanner
  - Source: Key Management Service
    Target: Key_Management_Service
  SourceDir: Security
- Name: Storage
  Services:
  - Source: Cloud Filestore
    Target: Cloud_Filestore
  - Source: Cloud Storage
    Target: Cloud_Storage
  - Source: Persistent Disk
    Target: Persistent_Disk
  SourceDir: Storage
Defaults:
  Category:
    Color: SquidInk
  Colors:
    SquidInk: '#232F3E'
  TargetMaxSize: 64
